### PR TITLE
use 'repeat' for default wrapping as on shadertoy.com

### PR DESCRIPTION
**Pull request by micahscopes**
the current shadertoy sampler defaults:
image

### CODE REVIEW

**Comment by fmenozzi** [comment]
I'm confused by the image: is the default tile or repeat?

**Comment by micahscopes** [comment]
Ah, those are the same, shadertoy calls it "repeat" and gfx-rs calls it "tile".  I suppose I could change the name to "repeat" to match shadertoy?

**Comment by fmenozzi** [comment]
Ah right. In that case, yeah let's change the name to repeat to match shadertoy's terminology.

**Comment by micahscopes** [comment]
Should be good now!

**Comment by fmenozzi** [comment]
Perfect, thanks!

**Comment by micahscopes** [comment]
Thanks for fielding all these PRs!  This is a super useful tool and it works great with the upcoming release of OBS which lets you set the blend mode on sources.  The fact that shadertoy-rs doesn't add a background when `alpha=0` is in my opinion perfect and makes it easier to use these shadertoy-rs windows as sources for compositing in OBS. :nerd_face:

**Comment by fmenozzi** [comment]
Thanks so much for your contributions! I'm happy to hear that this is useful to at least one person out there!

**Pull request merged**
